<?php

namespace Modules\Media\Enums;

enum MediaCollectionType: string
{
    case UNASSIGNED = 'UNASSIGNED';
    case AVATAR = 'AVATAR';
    case BANNER = 'BANNER';

    case PORTFOLIO_IMAGES = 'PORTFOLIO_IMAGES';
    case CERTIFICATE_IMAGE = 'CERTIFICATE_IMAGE';

    case PROJECT_IMAGES = 'PROJECT_IMAGES';
    case PROPOSAL_ATTACHMENTS = 'PROPOSAL_ATTACHMENTS';

    case CHAT_MESSAGE_ATTACHMENTS = 'CHAT_MESSAGE_ATTACHMENTS';
}
